export default {
  welcome: "Welcome!",
  email: "Email address",
  invalidEmail: "Email incorrect!",
  password: "Password",
  invalidPassword: "Password incorrect!",
  confirmPassword: "Confirm password",
  invalidConfirmPassword: "Password does not match!",
  login: "Login",
  messageAccont: "Don't have an account?",
  register: "Register",
  yourName: "Your name",
  invalidName: "Name incorrect!",
  lastname: "Last name",
  invalidLastName: "Last name incorrect!",
  searchHere: "Search here",
  listMode: "List",
  gridMode: "Grid",
  dashboard: "Dashboard",
  archivedView: "Archived",
  category: "Category",
  Personal: "Personal",
  Health: "Health",
  Education: "Education",
  Work: "Work",
  Others: "Others",
  status: "Status",
  Pending: "Pending",
  InProgress: "In Progress",
  Completed: "Completed",
  importance: "Importance",
  Low: "Low",
  Medium: "Medium",
  High: "High",
  all: "All",
  addTodo: "Add a todo",
  addTodoTitle: "Add TODO",
  titleAddTodo: "Title:",
  myFirstTodo: "My First Todo",
  isRequiredTitle: "Title is required",
  descriptionAddTodo: "Description:",
  describeMyFirtsTodo: "Describing my first todo...",
  descriptionIsRequired: "Description is required",
  selectAnOption: "Select an option",
  cancel: "Cancel",
  save: "Save",
  editTodo: "Edit your TODO",
}