export default {
  welcome: "Welcome!",
  email: "Email address",
  invalidEmail: "Email incorrect!",
  password: "Password",
  invalidPassword: "Password incorrect!",
  confirmPassword: "Confirm password",
  invalidConfirmPassword: "Password does not match!",
  login: "Login",
  messageAccountLogin: "Don't have an account?",
  messageAccountRegister: "Do you have an account?",
  register: "Register",
  yourName: "Your name",
  invalidName: "Name incorrect!",
  lastname: "Last name",
  invalidLastName: "Last name incorrect!",
  searchHere: "Search here",
  listMode: "List",
  gridMode: "Grid",
  dashboard: "Dashboard",
  archivedView: "Archived",
  category: "Category",
  Personal: "Personal",
  Health: "Health",
  Education: "Education",
  Work: "Work",
  Others: "Others",
  status: "Status",
  Pending: "Pending",
  InProgress: "In Progress",
  Completed: "Completed",
  importance: "Importance",
  Low: "Low",
  Medium: "Medium",
  High: "High",
  all: "All",
  addTodo: "Add a todo",
  addTodoTitle: "Add TODO",
  titleAddTodo: "Title:",
  myFirstTodo: "My First Todo",
  isRequiredTitle: "Title is required",
  descriptionAddTodo: "Description:",
  describeMyFirtsTodo: "Describing my first todo...",
  descriptionIsRequired: "Description is required",
  selectAnOption: "Select an option",
  cancel: "Cancel",
  save: "Save",
  editTodo: "Edit your TODO",
  title: "Title",
  description: "Description",
  delete: "Delete",
  iconArchived: "Archive",
  unarchive: "Unarchive",
  confirmDeleteTodo: "Are you sure you want to delete your todo?",
  confirm: "Confirm",
  altImageTodo: "Task image",
  loadingSpinner: "Loading...",
  todoListApp: "Todo list app",
  profile: "Profile",
  authPages: "Auth pages",
  logout: "Logout",
  addInformationYouSelft: "Add information about yourself",
  account: "Account",
  personalInfo: "Personal info",
  incorrectOrEmptyEmail: "Incorrect or empty email",
  name: "Name",
  incorrectNameOrEmpty: "Incorrect or empty name",
  incorrectLastNameOrEmpty: "Incorrect or empty last name",
  yourEmail: "Your email",
  yourLastName: "Your last name",
  changePassword: "Change password",
  passwordIsRequiredMessage: "The current password is required to make any data changes to your account.",
  currentPassword: "Your current password",
  passwordRequired: "Password is required",
  newPassword: "New password",
  yourNewPassword: "Your new password",
  requiredNewpasswordMessage: "The password must contain 8 characters including a number.",
  update: "Update",
  deleteAccount: "Delete account",
  confirmDeleteAccount: "Are you sure you want to delete your account?",
  actions: "Actions",
  rolIncorrect: "You do not have the permissions to delete this account",
}