export const diccionary = {
  es:{
    welcome: "Bienvenido!",
    email: "Dirección de correo electrónico",
    invalidEmail: "¡Correo electrónico incorrecto!",
    password: "Contraseña",
    invalidPassword: "¡Contraseña incorrecta!",
    confirmPassword: "Confirmar Contraseña",
    invalidConfirmPassword: "¡Las contraseñas no coinciden!",
    login: "Iniciar session",
    messageAccont: "¿No tienes una cuenta?",
    register: "Regístrate",
    yourName: "Tu nombre",
    invalidName: "Nombre incorrecto",
    lastname: "Apellidos",
    invalidLastName: "¡Apellido incorrecto!",
    searchHere: "Busca aquí",
    listMode:"Lista",
    gridMode: "Cuadrícula",
    dashboard: "Panel",
    archivedView: "Archivadas",
    category: "Categoría",
    Personal: "Personal",
    Health: "Salud",
    Education: "Educación",
    Work: "Trabajo",
    Others: "Otros",
    status: "Estado",
    Pending: "Pendiente",
    InProgress: "En progreso",
    Completed: "Completado",
    importance: "Importancia",
    Low: "Baja",
    Medium: "Media",
    High: "Alta",
    all: "Todas"

  }, 
  en:{
    welcome: "Welcome!",
    email: "Email address",
    invalidEmail: "Email incorrect!",
    password: "Password",
    invalidPassword: "Password incorrect!",
    confirmPassword: "Confirm password",
    invalidConfirmPassword: "Password does not match!",
    login: "Login",
    messageAccont: "Don't have an account?",
    register: "Register",
    yourName: "Your name",
    invalidName: "Name incorrect!",
    lastname: "Last name",
    invalidLastName: "Last name incorrect!",
    searchHere: "Search here",
    listMode:"List",
    gridMode: "Grid",
    dashboard: "Dashboard",
    archivedView: "Archived",
    category: "Category",
    Personal: "Personal",
    Health: "Health",
    Education: "Education",
    Work: "Work",
    Others: "Others",
    status: "Status",
    Pending: "Pending",
    InProgress: "In Progress",
    Completed: "Completed",
    importance: "Importance",
    Low: "Low",
    Medium: "Medium",
    High: "High",
    all: "All"

  }
}

