export default {
  welcome: "Bienvenido!",
  email: "Dirección de correo electrónico",
  invalidEmail: "¡Correo electrónico incorrecto!",
  password: "Contraseña",
  invalidPassword: "¡Contraseña incorrecta!",
  confirmPassword: "Confirmar Contraseña",
  invalidConfirmPassword: "¡Las contraseñas no coinciden!",
  login: "Iniciar sesión",
  messageAccountLogin: "¿No tienes una cuenta?",
  messageAccountRegister: "¿Tienes una cuenta?",
  register: "Regístrate",
  yourName: "Tu nombre",
  invalidName: "Nombre incorrecto",
  lastname: "Apellidos",
  invalidLastName: "¡Apellido incorrecto!",
  searchHere: "Busca aquí",
  listMode: "Lista",
  gridMode: "Cuadrícula",
  dashboard: "Panel",
  archivedView: "Archivadas",
  category: "Categoría",
  Personal: "Personal",
  Health: "Salud",
  Education: "Educación",
  Work: "Trabajo",
  Others: "Otros",
  status: "Estado",
  Pending: "Pendiente",
  InProgress: "En progreso",
  Completed: "Completado",
  importance: "Importancia",
  Low: "Baja",
  Medium: "Media",
  High: "Alta",
  all: "Todas",
  addTodo: "Agrega una tarea",
  addTodoTitle: "Agregar tarea",
  titleAddTodo: "Titulo:",
  myFirstTodo: "Mi primera tarea",
  isRequiredTitle: "El título es requerido",
  descriptionAddTodo: "Descripción:",
  describeMyFirtsTodo: "Describiendo mi primera tarea...",
  descriptionIsRequired: "La descripción es requerida",
  selectAnOption: "Seleccione una opción",
  cancel: "Cancelar",
  save: "Guardar",
  editTodo: "Edita tu tarea",
  title: "Titulo",
  description: "Descripción",
  delete: "Eliminar",
  iconArchived: "Archivar",
  unarchive: "Desarchivar",
  confirmDeleteTodo: "¿Estás seguro de que quieres Eliminar tu tarea?",
  confirm: "Confirmar",
  altImageTodo: "Task image",
  loadingSpinner: "Cargando...",
  todoListApp: "Lista de tareas",
  profile: "Perfil",
  authPages: "Páginas de autorización",
  logout: "Cerrar sessión",
  addInformationYouSelft: "Añade información sobre ti",
  account: "Cuenta",
  personalInfo: "Información personal",
  incorrectOrEmptyEmail: "Correo electrónico incorrecto o vacío",
  name: "Nombre",
  incorrectNameOrEmpty: "Nombre incorrecto o vacío",
  incorrectLastNameOrEmpty: "Apellido incorrecto o vacío",
  yourEmail: "Tu email",
  yourLastName: "Tu apellido",
  changePassword: "Cambio de contraseña",
  passwordIsRequiredMessage: "La contraseña actual es necesaria para realizar cualquier cambio de datos en su cuenta.",
  currentPassword: "Tu contraseña actual",
  passwordRequired: "Se requiere contraseña",
  newPassword: "Nueva contraseña",
  yourNewPassword: "Tu nueva contraseña",
  requiredNewpasswordMessage: "La contraseña debe contener 8 caracteres, incluido un número.",
  update: "Actulizar",
  deleteAccount: "Eliminar cuenta",
  confirmDeleteAccount: "¿Segur/a que quieres eliminar tu cuenta?",
  actions: "Acciones",
  rolIncorrect: "No tienes los permisos para eliminar esta cuenta",
}
