export default {
  welcome: "Bienvenido!",
  email: "Dirección de correo electrónico",
  invalidEmail: "¡Correo electrónico incorrecto!",
  password: "Contraseña",
  invalidPassword: "¡Contraseña incorrecta!",
  confirmPassword: "Confirmar Contraseña",
  invalidConfirmPassword: "¡Las contraseñas no coinciden!",
  login: "Iniciar session",
  messageAccont: "¿No tienes una cuenta?",
  register: "Regístrate",
  yourName: "Tu nombre",
  invalidName: "Nombre incorrecto",
  lastname: "Apellidos",
  invalidLastName: "¡Apellido incorrecto!",
  searchHere: "Busca aquí",
  listMode: "Lista",
  gridMode: "Cuadrícula",
  dashboard: "Panel",
  archivedView: "Archivadas",
  category: "Categoría",
  Personal: "Personal",
  Health: "Salud",
  Education: "Educación",
  Work: "Trabajo",
  Others: "Otros",
  status: "Estado",
  Pending: "Pendiente",
  InProgress: "En progreso",
  Completed: "Completado",
  importance: "Importancia",
  Low: "Baja",
  Medium: "Media",
  High: "Alta",
  all: "Todas",
  addTodo: "Agrega una tarea",
  addTodoTitle: "Agregar tarea",
  titleAddTodo: "Titulo:",
  myFirstTodo: "Mi primera tarea",
  isRequiredTitle: "El título es requerido",
  descriptionAddTodo: "Descripción:",
  describeMyFirtsTodo: "Describiendo mi primera tarea...",
  descriptionIsRequired: "La descripción es requerida",
  selectAnOption: "Seleccione una opción",
  cancel: "Cancelar",
  save: "Guardar",
  editTodo: "Edita tu tarea",

}